universe = vanilla
executable = sh_files/run_brain_pipeline.sh
arguments = $(jobname)
getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

output = logs/$(jobname).$(Cluster).$(Process).out
error = logs/$(jobname).$(Cluster).$(Process).err
log = logs/$(jobname).$(Cluster).$(Process).log

request_cpus = 4
request_memory = 12GB
request_disk = 20GB

queue 1