# HTCondor Submit File for Hemisphere Data Splitting
universe = vanilla
executable = cluster/hemisphere/03_train_hemisphere_ovr.sh

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 8             
request_memory = 3GB
request_disk = 2GB

# Log files
output = logs/03_hemisphere_ovr.out
error = logs/03_hemisphere_ovr.err
log = logs/03_hemisphere_ovr.log

# Single job - processes both datasets
queue 1
