# HTCondor Submit File for Hemisphere Data Splitting
universe = vanilla
executable = cluster/condor/hemisphere/02_train_hemisphere_multinomial.sh

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 32             
request_memory = 128GB
request_disk = 5GB

# Log files
output = logs/hemisphere_multinomial.out
error = logs/hemisphere_multinomial.err
log = logs/hemisphere_multinomial.log

# Single job - processes both datasets
queue 1
