# HTCondor Submit File for Hemisphere Data Splitting
universe = vanilla
executable = cluster/condor/hemisphere/04_train_hemisphere_ovo.sh

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 32             
request_memory = 128GB
request_disk = 5GB

# Log files
output = logs/04_hemisphere_ovo.out
error = logs/04_hemisphere_ovo.err
log = logs/04_hemisphere_ovo.log

# Single job - processes both datasets
queue 1
