# HTCondor Submit File for FC Data Splitting
universe = vanilla
executable = cluster/condor/FC_pipeline/02_train_FC_ovr.sh

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 32             
request_memory = 128GB
request_disk = 5GB

# Log files
output = logs/02_FC_ovr.out
error = logs/02_FC_ovr.err
log = logs/02_FC_ovr.log

# Single job - processes both datasets
queue 1
