universe = vanilla
executable = CONDOR/scripts/precision_alpha_tuning.sh
arguments = $(alpha)

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

request_cpus = 5
request_memory = 3GB
request_disk = 2GB

output = logs/precision_alpha/alpha_$(alpha).out
error  = logs/precision_alpha/alpha_$(alpha).err
log    = logs/precision_alpha/alpha_$(alpha).log

queue alpha from (
    0.001
    0.01
    0.1
    0.5
    1.5
)