# HTCondor Submit File for Hyperparameter Search
universe = vanilla
executable = CONDOR/scripts/run_hyperparameter_search.sh

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 10                
request_memory = 128GB
request_disk = 2GB

output = logs/hypersearch.out
error = logs/hypersearch.err
log = logs/hypersearch.log

# Single job running all outer CV folds
queue 1
