universe = vanilla
executable = CONDOR/scripts/run_brain_pipeline.sh 

arguments = "\
--experiment-name Exp_LR_NM_bestparam \
--model best_from_search \
--stage 1"

jobname = Exp_LR_NM_bestparam

initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

output = logs/$(jobname).$(Cluster).$(Process).out
error = logs/$(jobname).$(Cluster).$(Process).err
log = logs/$(jobname).$(Cluster).$(Process).log

request_cpus = 8
request_memory = 2GB
request_disk = 10GB

queue 1