# HTCondor Submit File for Hyperparameter Search
universe = vanilla
executable = CONDOR/scripts/run_hyperparameter_search.sh
arguments = $(Process)

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Resources for Job 
request_cpus = 32                
request_memory = 32GB
request_disk = 15GB

output = logs/hypersearch_$(Process).out
error = logs/hypersearch_$(Process).err
log = logs/hypersearch_$(Process).log

# 20 jobs / iterations
queue 20                        
