# HTCondor Submit File for Hyperparameter Search
universe = vanilla
executable = sh_files/run_hyperparameter_search.sh
arguments = $(Process)

getenv = True
initialdir = /home/sjoon/projects/brain_connectivity_classifier/

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

request_cpus = 4
request_memory = 12GB
request_disk = 15GB

output = logs/hypersearch_$(Process).out
error = logs/hypersearch_$(Process).err
log = logs/hypersearch_$(Process).log

queue 20
